### ISSUE TITLE
Colab error.

### ISSUE THREAD

**Issue by xiaocc612** [brjathu/PHALP#1]
At first, thanks for sharing your wondful work. It seems that the demo can't output desired results.
`out/Videos_results/PHALP_demo_youtube_0.mp4: No such file or directory
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-11-fda5b58ee808>](https://localhost:8080/#) in <module>()
     11 
     12 get_ipython().system('ffmpeg -i out/Videos_results/PHALP_demo_youtube_0.mp4 out/Videos_results/PHALP_demo_youtube_0_ffmpeg.mp4')
---> 13 show_local_mp4_video('out/Videos_results/PHALP_demo_youtube_0_ffmpeg.mp4', width=960, height=540)

[<ipython-input-11-fda5b58ee808>](https://localhost:8080/#) in show_local_mp4_video(file_name, width, height)
      4   import base64
      5   from IPython.display import HTML
----> 6   video_encoded = base64.b64encode(io.open(file_name, 'rb').read())
      7   return HTML(data='''<video width="{0}" height="{1}" alt="test" controls>
      8                       <source src="data:video/mp4;base64,{2}" type="video/mp4" />

FileNotFoundError: [Errno 2] No such file or directory: 'out/Videos_results/PHALP_demo_youtube_0_ffmpeg.mp4'`

And there is no output file in the `/content/PHALP/out/Videos_results/results`.   ):

**Comment by brjathu** [comment]
Hi, It seems the first part of the run demo section, fails randomly (could be something to do with pytube).
It is working fine on our end. Can you please try again.

**Comment by xiaocc612** [comment]
It works fine now, thank you.
