### ISSUE TITLE
About the options of opt.predict

### ISSUE THREAD

**Issue by nnop** [brjathu/PHALP#11]
Thanks for the great work. I have a question about the `opt.predict` script argument.

The `predict` argumetn in the demo script is `TPL`:
https://github.com/brjathu/PHALP/blob/901698d1cce76f06f103f4ac0d891f17a245c6ba/scripts/_demo.sh#L9

However, I also saw there is a `A` option in the code:
https://github.com/brjathu/PHALP/blob/55309d529f1f679be34bd26cdea142a212e7ddec/deep_sort_/nn_matching.py#L73-L76

It seem being related with the appearance distance.
What's the purpose of option `A`, would it be helpful if I add it in `opt.predict`?

**Comment by brjathu** [comment]
Thanks for this find, "T" is for computing appearance distance using the predicted texture map, and "A" is for computing appearance distance in embedding space of single frame texture map. The algorithm can uses either of of these option.  The appearance vector (corresponding to A) is not predicted over time, so I would recommend using "T" as the default option.

**Comment by nnop** [comment]
Thanks for the quick respondence.
