### ISSUE TITLE
Difference between 'tid' and 'tracked_ids', 'bbox' and 'tracked_bbox'.

### ISSUE THREAD

**Issue by zhixuany** [brjathu/PHALP#12]
Thanks for the fantastic work! 
While I am playing around with the code, I am a little bit confused about the difference in meaning between two pairs of keys, i.e. 'tid' vs  'tracked_ids', and 'bbox' v.s. 'tracked_bbox'. It seems that they are equivalent if "tracks_.time_since_update==0" is true. Could you provide some explanations here? Thanks!!

**Comment by brjathu** [comment]
Hi, thanks for your interest in our work and apologies for the confusion. 
Yes you are correct. if "tracked_time" is 0, then "tid", "bbox" are from the current detection, else these belongs to the last seen detection of the track.  "tid", "bbox" both are always updated and you could use "tracked_time"==0, to filter the true detection. On the other hand, 'tracked_ids','tracked_bbox' are updated only if there is a fresh new detection to be appended to the track. (https://github.com/brjathu/PHALP/blob/901698d1cce76f06f103f4ac0d891f17a245c6ba/demo_online.py#L106)

Hope this explains the keys, please feel free to ask any question for more explanation.

**Comment by brjathu** [comment]
you meant "If a tracklet do not have have matched detection"? if so you are correct. These copies are used to visualize "ghosts" where there location and pose will be updates with our prediction model, for example at occlusion. You can visualize them by setting `GHOST_FULL_FAST` in the render type.

**Comment by zhixuany** [comment]
Yes, sorry that is a typo. 

Got it! Thank you very much!
