### ISSUE TITLE
How to converting Posetrack format GT to be the one in this project?

### ISSUE THREAD

**Issue by zhenzhiwang** [brjathu/PHALP#13]
Hi brjathu,

Thanks for sharing your great work! I am wondering how you convert the original Posetrack groundtruth to be the one you used in this repo? I want to train this method but find no suitable groundtruth for the training set. I will really appreciate if you could provide the script for converting the GT format. Thank you again.

**Comment by zhenzhiwang** [comment]
Yes I need the script to create `posetrack_gt_data.pickle` file.  Thank you a lot!

**Comment by brjathu** [comment]
Thanks, We haven't trained any neural networks with tracking data. We just optimized 4 numbers for the distance function (https://github.com/brjathu/PHALP/blob/92206ec13310dfd6dd6a8fb01c97aac8ca82ae96/deep_sort_/nn_matching.py#L86). We will release the optimization code as soon as possible.
