### ISSUE TITLE
HMAR training code

### ISSUE THREAD

**Issue by chaitanya100100** [brjathu/PHALP#16]
Do you plan to release HMAR training code?
T3DP also uses HMAR but I couldn't find HMAR training code there also.

**Comment by brjathu** [comment]
Hi,

Apologies for the delay in getting back, We haven't released the HMAR code (to train the appearance head), but our new work (https://github.com/shubham-goel/4D-Humans) has all the ingredients to train the new hmr2 model. We will also release a better sampling approach to get better appearance features directly from hmr2 model.

**Comment by chaitanya100100** [comment]
Thanks!! Looking forward to it.
