### ISSUE TITLE
Parameters in the smpl_mean_params.npz file

### ISSUE THREAD

**Issue by 1309723614** [brjathu/PHALP#17]
Hello author, thanks for your excellent work.

But I have a problem:
I would like to know what the data in [brjathu/PHALP](https://github.com/brjathu/PHALP/blob/475b1d191d45fb5703cb3f8f1c02212a0c05dc6d/phalp/trackers/PHALP.py#L620) mean.

[:, [0]] means global_orient
[:, 1:24] means body_pose

What about the others?Please reply to me at your earliest convenience. Thanks a million.

**Comment by brjathu** [comment]
```
>>> npz.files
['pose', 'shape', 'cam']
```
pose is global_orient and body_pose in 6D rotation representation.
(1+23)*6, mean pose params then convert to 6D-> rotMat.

shape is the average body shape beta_0 that the HMR iterative regressor starts from.
cam is the default camera p_0 that the iterative regressor starts from

**Comment by 1309723614** [comment]
I see. Thank you very much
