### ISSUE TITLE
About the training code.

### ISSUE THREAD

**Issue by xiaocc612** [brjathu/PHALP#2]
Hi, thank you for your wondful work.  When will the the training code be released?

**Comment by brjathu** [comment]
Hi, Thank you very for your interest in our work, and apologies for the late reply. 
For PHALP the training is simple optimization on learning 5 parameters, we will release this code soon, but right now the priority is on releasing the datasets (AVA) and evaluation codes. So hopefully the optimization code will be released in about a week.

**Comment by xiaocc612** [comment]
Thank you your reply and have a nice day. : )

**Comment by xiaocc612** [comment]
> Hi, Thank you very for your interest in our work, and apologies for the late reply. For PHALP the training is simple optimization on learning 5 parameters, we will release this code soon, but right now the priority is on releasing the datasets (AVA) and evaluation codes. So hopefully the optimization code will be released in about a week.


How long before the AVA dataset and the training code are released? I'm very much looking forward to it.

**Comment by xiaocc612** [comment]
> Hi, Thank you very for your interest in our work, and apologies for the late reply. For PHALP the training is simple optimization on learning 5 parameters, we will release this code soon, but right now the priority is on releasing the datasets (AVA) and evaluation codes. So hopefully the optimization code will be released in about a week.

Is the preprocessed AVA dataset available now?
