### ISSUE TITLE
Cannot install detectron2

### ISSUE THREAD

**Issue by tghim** [brjathu/PHALP#20]
First of all, thank you for sharing your great work!
I was really excited after reading your papers and I want to see how it works.

Unfortunately, whenever I try to install your frameworks, I get problems installing detectron2
with the error message "ERROR: Could not build wheels for detectron2, which is required to install pyproject.toml-based projects"
I tried to install detectron2 from the official detectron git, but it failed. 

My environment is Ubuntu 22.04 with RTX 4090, cuda 11.8, and checked out that cuda is available in your conda environment(cuda 11.6+torch 1.13.1) 
How could you use detectron2 in all of your frameworks?

I would really appreciate your reply and sorry to disturb you.
Thanks!

**Comment by brjathu** [comment]
Apologies for the late reply, is the resolved?

**Comment by tghim** [comment]
I solved this by changing the machine. 
Since detectron2 could not be installed on my RTX 4090, I ended up running it on the lab server RTX 3090 (Ubuntu 20.04, cuda 11.1+torch 1.13.1) and it was successful. 
It hasn't been successful yet on the 4090 RTX.

**Comment by brjathu** [comment]
Thanks for the update. I haven't tested it on 4090, but the code worked on 3060, 3090, and A100, V100.

**Comment by tghim** [comment]
Ok. I'll close this issue for now.
