### ISSUE TITLE
Download links are dead!

### ISSUE THREAD

**Issue by ldtho** [brjathu/PHALP#23]
Hi @brjathu,
Thank you for the great work, I just want to ask if you can provide the files via Google Drive? Looks like the download links that contain people.eecs.berkeley.edu are not accessible. 

https://people.eecs.berkeley.edu/~jathushan/projects/phalp/ava/lart_mvit.config
https://people.eecs.berkeley.edu/~jathushan/projects/phalp/ava/lart_mvit.ckpt
https://people.eecs.berkeley.edu/~jathushan/projects/phalp/ava/mvit.yaml
https://people.eecs.berkeley.edu/~jathushan/projects/phalp/ava/mvit.pyth

I tried to access people.eecs.berkeley.edu but no luck, 
Thanks for your help
Regards

**Comment by ldtho** [comment]
Oh the links are working now, thank you, please ignore this issue :)

**Comment by lishisen01** [comment]
https://people.eecs.berkeley.edu/~jathushan/projects/phalp/3D/head_faces.npy
https://people.eecs.berkeley.edu/~jathushan/projects/phalp/3D/mean_std.npy
https://people.eecs.berkeley.edu/~jathushan/projects/phalp/3D/smpl_mean_params.npz
https://people.eecs.berkeley.edu/~jathushan/projects/phalp/3D/SMPL_to_J19.pkl
https://people.eecs.berkeley.edu/~jathushan/projects/phalp/3D/texture.npz
https://people.eecs.berkeley.edu/~jathushan/projects/phalp/bmap_256.npy
https://people.eecs.berkeley.edu/~jathushan/projects/phalp/fmap_256.npy
https://people.eecs.berkeley.edu/~jathushan/projects/phalp/weights/hmar_v2_weights.pth
https://people.eecs.berkeley.edu/~jathushan/projects/phalp/weights/pose_predictor_40006.ckpt
https://people.eecs.berkeley.edu/~jathushan/projects/phalp/weights/config_40006.yaml
https://people.eecs.berkeley.edu/~jathushan/projects/phalp/ava/ava_labels.pkl
https://people.eecs.berkeley.edu/~jathushan/projects/phalp/ava/ava_class_mappping.pkl
When I was accessing these downloaded files, the links were all broken. Can anyone help me find where I can still find a backup of the files? Or if anyone has saved a backup of this file, could you please share it with me? Thank you so much
