### ISSUE TITLE
The download links do not work

### ISSUE THREAD

**Issue by tinatiansjz** [brjathu/PHALP#25]
Thanks for sharing us with this great work~
I am trying to setup the environment and run the demo, but I notice that [the download links](https://github.com/brjathu/PHALP/blob/master/phalp/trackers/PHALP.py#L670) fail to redirect to files. Can you tell me the updated download links?

**Comment by tinatiansjz** [comment]
Yeah... I figured it out. Files can be accessed through [here](https://people.eecs.berkeley.edu/~jathushan/projects/phalp/).

**Comment by yuriokamoto** [comment]
https://people.eecs.berkeley.edu/~jathushan/projects/phalp/
I cannot open this link.Is there a problem with the site?
