### ISSUE TITLE
Hi, there was a problem with the rendering of the video results.

### ISSUE THREAD

**Issue by yanmn** [brjathu/PHALP#35]
I find an error in py_renderer.py line120 : 

` operands could not be broadcast together with shapes (1280,1280,3) (1280,1280,0) 
Traceback (most recent call last):
  File "phalp/trackers/PHALP.py", line 252, in track
    rendered_, f_size = self.visualizer.render_video(final_visuals_dic[frame_key])
  File "phalp/visualize/visualizer.py", line 359, in render_video
    rendered_image_final, valid_mask  = self.render_single_frame(
  File "phalp/visualize/visualizer.py", line 77, in render_single_frame
    rgb_from_pred, validmask = self.render.visualize_all(pred_vertices.numpy(), pred_cam_t_bs.cpu().numpy(), color, image, use_image=use_image)
  File "phalp/visualize/py_renderer.py", line 120, in visualize_all
    output_img = color[:, :, :3] * valid_mask + (1 - valid_mask) * images
ValueError: operands could not be broadcast together with shapes (1280,1280,3) (1280,1280,0) `

So, I forced to unify the dimensions.

`118   valid_mask = color[:,:,3:4]

      119   if valid_mask.shape[-1] == 0:

      120       valid_mask = np.ones((valid_mask.shape[0], valid_mask.shape[1], 1), dtype=valid_mask.dtype)

      121   if(use_image):

      122       output_img = color[:, :, :3] * valid_mask + (1 - valid_mask) * images`

As a result, there is no video picture.

![Snipaste_2024-05-15_18-42-38](https://github.com/brjathu/PHALP/assets/33342302/5156369c-554b-41f9-95da-0ab3be2348e2)

How to solve this problem? Why is the error _"operands could not be broadcast together with shapes (1280,1280,3) (1280,1280,0)"_?

**Comment by geopavlakos** [comment]
What is the original video that created this issue for you?

**Comment by geopavlakos** [comment]
The provided video is expected to work out of the box. Is it possible that there is some problem with your installation? Could you try with a clean virtual environment?

**Comment by yanmn** [comment]
I have solved this problem, thank you very much for your answer!


Are PHALP_v2 and PHALP_v2_pymafx open source?


def get_tracker(cfg):
&nbsp; &nbsp; from phalp.trackers.PHALP import PHALP
&nbsp; &nbsp; """Get the tracker object from the config."""
&nbsp; &nbsp; if cfg.base_tracker == "PHALP":
&nbsp; &nbsp; &nbsp; &nbsp; return PHALP(cfg)
&nbsp; &nbsp; elif cfg.base_tracker == "PHALP_v2":
&nbsp; &nbsp; &nbsp; &nbsp; return PHALP_v2(cfg)
&nbsp; &nbsp; elif cfg.base_tracker == "PHALP_v2_pymafx":
&nbsp; &nbsp; &nbsp; &nbsp; return PHALP_v2_pymafx(cfg)
&nbsp; &nbsp; else:
&nbsp; &nbsp; &nbsp; &nbsp; raise ValueError("Unknown tracker")




yanming
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "brjathu/PHALP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月22日(星期三) 晚上11:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [brjathu/PHALP] Hi, there was a problem with the rendering of the video results. (Issue #35)





 
The provided video is expected to work out of the box. Is it possible that there is some problem with your installation? Could you try with a clean virtual environment?

**Comment by lburzawa** [comment]
@yanmn I have same problem, how did you resolve it?
