### ISSUE TITLE
Effect of `GHOST` in render_type

### ISSUE THREAD

**Issue by sdy-ny** [brjathu/PHALP#4]
Hi, does `final_visuals_dic` in demo_online.py contain all the ghost detections by default?

I thought each track would have ghost detections up to `max_age` after it disappears, but it seems that it's not the case. Could you explain how long the ghost detections are kept for?

Thanks!

**Comment by brjathu** [comment]
Can you try, `GHOST_SMOOTH`.

Yes, final_visuals_dic stores all the information. But I edited the code yesterday to delete it after every frame to speed it up.
Please delete this line (https://github.com/brjathu/PHALP/blob/0502c0aa515292bc70e358fe3b3ec65e63215327/demo_online.py#L229) if you want to store it.

**Comment by sdy-ny** [comment]
Thank you!
