### ISSUE TITLE
"glGetError" while running the demo

### ISSUE THREAD

**Issue by gmindflow** [brjathu/PHALP#7]
While running the demo code as given,
"python3 demo_online.py --youtube_link xEH_5T9jMVU --start_frame 1250 --end_frame 1400",

I am having a error on glGetError saying, "AttributeError: 'NoneType' object has no attribute 'glGetError'".
Did anyone else had this error and was able to solve it?

**Comment by brjathu** [comment]
Hi, someone else are reported this issue [here](https://github.com/MPI-IS/mesh/issues/23#issuecomment-770860939). Can you replace `_ErrorChecker( _p, _p.GL.glGetError)` function with `None`. It worked on our end. Thanks.
